name: CI Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build-solution:
    runs-on: windows-latest

    steps:
    # Checkout my repository for workflow
    - name: Checkout code
      uses: actions/checkout@v2

    # Used to build solution
    - name: Setup MSBuild 
      uses: microsoft/setup-msbuild@v1
      
    # Used to run all MSUnit Tests
    - name: Setup VSTest Path 
      uses: darenm/Setup-VSTest@v1.2
      
    # Sets up package manager
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    # Restores any packages or dependancies
    - name: Restore NuGet packages
      run: nuget restore ASE_Assignment.sln
      
    # Builds my solution
    - name: Build solution
      run: msbuild ASE_Assignment.sln
      
    # Runs all my Unit Tests (check logs to see test results)
    - name: Run unit tests
      run: vstest.console.exe /Platform:x64 ".\Test-Project\bin\Debug\Unit-Tests.dll"

