name: PR Labeler

on:
  pull_request_target:
    branches: ["*"]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label PR title
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true